######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 28 10:13:32 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

HEADERS += \
    stat.h
