/*! ver:1430984032 Copyright 2015 Baidu Inc. All Rights Reserved. */;(function(){var l=void 0,n=!0,s=null,u=!1,E=window.BAIDU_DUP_require,H=window.BAIDU_DUP_define;
H&&H("union/common/oo1430984032",[],function(){function g(b){var e=g.create(g);return b.call(e,e,e.sb)}function f(b,e){if(b.constructor===Array)for(var d=0,a=b.length;d<a;d++){if(e.call(b,b[d],d,b)===u)return u}else{var d=!{toString:1}.propertyIsEnumerable("toString"),c="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(a in b)if(b.hasOwnProperty(a)&&e.call(b,b[a],a,b)===u)return u;if(d){d=0;for(a=c.length;d<a;d++){var f=c[d];if(b.hasOwnProperty(f)&&
e.call(b,f,d,b)===u)return u}}}return n}function e(b,e,d){f(e,function(a,c){if(!b.hasOwnProperty(c)||d)b[c]=a})}function h(b){function e(){}if(Object.create)return Object.create(b);e.prototype=b;return new e}g.sb={};g.create=h;g.bc=f;g.Ma=function(b){var f,d=b.hasOwnProperty("constructor")?b.constructor:function(){};d.prototype=b;d.prototype.constructor=d;f=f||{};f.kb&&e(d,f.kb);return d};g.extend=function(b,f,d){var a;a=f.hasOwnProperty("constructor")?f.constructor:function(){b.constructor.apply(this,
arguments)};a.prototype=h(b.prototype);e(a.prototype,f,n);a.prototype.constructor=a;a.prototype.Qc=b.prototype;e(a,b);d=d||{};d.kb&&e(a,d.kb,n);return a};g.gd=function(b){var e=this.sb;f(b.split("."),function(b){e.hasOwnProperty(b)||(e[b]={});e=e[b]});return e};g.i=function(b,e){var d;return function(){d=d||[];for(var a=0,c=arguments.length;a<c;a++)d.push(arguments[a]);return b.apply(e||{},d)}};return g});
H&&H("union/common/cookie1430984032",[],function(){return{V:function(g,f){var e,h=RegExp("(^| )"+g+"=([^;]*)(;|$)").exec((f||window).document.cookie);h&&(e=h[2]);return e},ga:function(g,f,e){var e=e||{},h=e.aa;"number"==typeof e.aa&&(h=new Date,h.setTime(h.getTime()+e.aa));document.cookie=""+g+"="+f+(e.path?"; path="+e.path:"")+(h?"; expires="+h.toGMTString():"")+(e.domain?"; domain="+e.domain:"")+(e.ld?"; secure":"")},remove:function(g){var f=new Date;f.setTime(f.getTime()-86400);this.ga(g,"",{path:"/",aa:f})}}});
H&&H("union/common/bom1430984032",[],function(){var g={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(g.g=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Xc=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(g.kd=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Tc=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.ed)&&
(g.fd=+RegExp.$1)}catch(f){}g.Fb=/webkit/i.test(navigator.userAgent);g.uc=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);g.Db="CSS1Compat"==document.compatMode;return{h:g,B:function(){var e=n;if(this.h.g&&(7>this.h.g||"BackCompat"===document.compatMode))e=u;return e},$c:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.scrollWidth:e.document.documentElement.scrollWidth}catch(f){return 0}},Zc:function(e){try{return e=e||window,"BackCompat"===
e.document.compatMode?e.document.body.scrollHeight:e.document.documentElement.scrollHeight}catch(f){return 0}},D:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientWidth:e.document.documentElement.clientWidth}catch(f){return 0}},o:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientHeight:e.document.documentElement.clientHeight}catch(f){return 0}},G:function(e){e=(e||window).document;return window.pageYOffset||e.documentElement.scrollTop||
e.body.scrollTop},$a:function(e){e=(e||window).document;return window.pageXOffset||e.documentElement.scrollLeft||e.body.scrollLeft},Gb:function(e){var f=u;try{e&&"object"===typeof e&&e.document&&"setInterval"in e&&(f=n)}catch(b){f=u}return f},oa:function(e){e=e||window;return e!=window.top&&e!=e.parent||!this.Gb(e)},Da:function(e,f){for(var f=2===arguments.length?f:e.parent,b=0;10>b++&&this.oa(e,f);){var i;try{i=!!e.parent.location.toString()}catch(d){i=u}if(!i)return n;e=e.parent}return 10<=b?n:
u},Ec:function(e,f){var b=new Image,i="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),f=f||window;f[i]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=s;b=f[i]=s};b.src=e},Ya:function(e){if(!e)return document;"string"===typeof e&&(e=document.getElementById(e));return 9===e.nodeType?e:e.ownerDocument||e.document},ab:function(e){"string"===typeof e&&(e=document.getElementById(e));e=this.Ya(e);return e.parentWindow||e.defaultView||s},bd:function(e){e=e||window;return this.oa(e)&&
!this.Da(e,e.top)&&this.Gb(e.top)?e.top:e}}});
H&&H("union/common/dom1430984032",["union/common/oo1430984032","union/common/bom1430984032"],function(g,f){return g(function(e){var g=f.h;return{m:function(b,e){return"string"===typeof b||b instanceof String?(e||window).document.getElementById(b):b},Cb:function(b,i){var d=n;if("string"===typeof i)return b.id===i;if(i.constructor===Object)return e.bc(i,function(a,c){var e=(b.getAttribute?b.getAttribute(c):b[c])||b[c];if("tagName"===c){if(e.toUpperCase()!=a.toUpperCase())return d=u}else if(e!=a)return d=u}),d;if(i.constructor===
Array){var a=i.concat([]);a.reverse();for(var c=b;c&&a.length;c=c.parentNode)this.Cb(c,a[0])&&a.shift();return!a.length?n:u}},Ob:function(b,e){if(b&&e(b)!==u){var d=b.childNodes;if(d)for(var a=0,c=d.length;a<c;a++)if(this.Ob(d[a],e)===u)return u}},Lb:function(b,e){var d=this;b.constructor===Object&&(b=this.s(b));if("string"===typeof e){for(var a=document.getElementById(e),c=a;c;){if(c===b)return a;c=c.parentNode}return s}if(e.constructor===Object){var f=s;d.Ob(b,function(a){if(d.Cb(a,e))return f=
a,u});return f}},s:function(b){if(b){if(b.nodeName)return b;1<arguments.length&&(b=Array.prototype.slice.call(arguments,0));if("string"===typeof b)return document.getElementById(b);if(b.constructor===Object)return this.Lb(document.documentElement,b);if(b.constructor===Array){for(var e=b.concat([]),d=document.documentElement;e.length&&d;)d=this.Lb(d,e.shift());return d}}},Cc:function(b,i,d){var d=d||this.pd||window,a=d.document;this.wb=0;this.da=this.da||[];this.da.push({Xa:b,vb:i||0,Ta:u});var c=
e.i(function(){var c=u;this.wb++;var b=u;try{d.frameElement&&(b=n)}catch(e){b=n}if(g.g&&9>g.g&&!b)try{a.documentElement.doScroll("left"),c=n}catch(i){}else if("complete"===a.readyState||this.ac)c=n;else if(3E5<this.wb){this.U&&(d.clearInterval(this.U),this.U=s);return}if(c)try{if(this.da&&this.da.length)for(var c=0,f=this.da.length;c<f;c++){var v=this.da[c];v&&v.Xa&&!v.Ta&&(v.vb?(v.Ta=n,d.setTimeout(v.Xa,v.vb)):(v.Ta=n,v.Xa()))}}catch(w){throw w;}finally{this.U&&(d.clearInterval(this.U),this.U=s)}},
this),b=e.i(function(){this.ac=n;c()},this);this.U||(this.U=d.setInterval(c,50),a.addEventListener?(a.addEventListener("DOMContentLoaded",b,u),d.addEventListener("load",b,u)):a.attachEvent&&d.attachEvent("onload",b,u))},B:function(){var b=n;if(g.g&&(7>g.g||"BackCompat"===document.compatMode))b=u;return b},bind:function(b,e,d){"string"===typeof b&&(b=this.s(b));e=e.replace(/^on/i,"").toLowerCase();b.addEventListener?b.addEventListener(e,d,u):b.attachEvent&&b.attachEvent("on"+e,d);return b},Pb:function(b,
e,d){b=this.s(b);if(!b)return s;e=e.replace(/^on/i,"").toLowerCase();b.removeEventListener?b.removeEventListener(e,d,u):b.detachEvent&&b.detachEvent("on"+e,d);return b},u:function(b,e){var d;"string"===typeof b&&(b=this.s(b));var a=f.Ya(b),c="",c=-1<e.indexOf("-")?e.replace(/[-_][^-_]{1}/g,function(a){return a.charAt(1).toUpperCase()}):e.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()});a&&a.defaultView&&a.defaultView.getComputedStyle?((a=a.defaultView.getComputedStyle(b,s))&&
(d=a.getPropertyValue(e)),"boolean"!==typeof d&&!d&&(d=a.getPropertyValue(c))):b.currentStyle&&((a=b.currentStyle)&&(d=a[e]),"boolean"!==typeof d&&!d&&(d=a[c]));return d},pc:function(b,e){e=e||window;"string"===typeof b&&(b=this.s(b));if(b){for(var d=this.ca(b),a,c=0;e!=e.parent&&10>c;)c++,a=this.ca(e.frameElement),d.left+=a.left,d.top+=a.top,e=e.parent;return d}},ca:function(b){"string"===typeof b&&(b=this.s(b));var e=f.Ya(b),d=f.h;0<d.uc&&e.getBoxObjectFor&&this.u(b,"position");var a={left:0,top:0},
c;if(b==(d.g&&!d.Db?e.body:e.documentElement)||!b)return a;if(b.getBoundingClientRect)b=b.getBoundingClientRect(),a.left=Math.floor(b.left)+Math.max(e.documentElement.scrollLeft,e.body.scrollLeft),a.top=Math.floor(b.top)+Math.max(e.documentElement.scrollTop,e.body.scrollTop),a.left-=e.documentElement.clientLeft,a.top-=e.documentElement.clientTop,b=e.body,e=parseInt(this.u(b,"borderLeftWidth"),10),b=parseInt(this.u(b,"borderTopWidth"),10),d.g&&!d.Db&&(a.left-=isNaN(e)?2:e,a.top-=isNaN(b)?2:b);else{c=
b;do{a.left+=c.offsetLeft;a.top+=c.offsetTop;if(0<d.Fb&&"fixed"==this.u(c,"position")){a.left+=e.body.scrollLeft;a.top+=e.body.scrollTop;break}c=c.offsetParent}while(c&&c!=b);if(0<d.opera||0<d.Fb&&"absolute"==this.u(b,"position"))a.top-=e.body.offsetTop;for(c=b.offsetParent;c&&c!=e.body;){a.left-=c.scrollLeft;if(!d.opera||"TR"!=c.tagName)a.top-=c.scrollTop;c=c.offsetParent}}return a},Ab:function(b,e){var b=this.s(b),d=b.offsetWidth;if(e||u)var a=this.u(b,"marginLeft").toString().toLowerCase().replace("px",
"").replace("auto","0"),c=this.u(b,"marginRight").toString().toLowerCase().replace("px","").replace("auto","0"),d=d+(parseInt(a||0,10)+parseInt(c||0,10));return d},zb:function(b,e){var b=this.s(b),d=b.offsetHeight;if(e||u)var a=this.u(b,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),c=this.u(b,"marginBottom").toString().toLowerCase().replace("px","").replace("auto","0"),d=d+(parseInt(a||0,10)+parseInt(c||0,10));return d},ad:function(b){var b=this.s(b),e=this.ab(b),d=0;
if(this.oa(window)&&!f.Da(window)){for(;e.parent!=window.top&&10>d;)d++,e=e.parent;10>d&&(b=e.frameElement||b)}return b},yb:function(b){var e=this.s(b),b=this.ab(e),d=100,a;try{for(;e&&e.tagName;){a=100;if(this.h.g){if(5<this.h.g)try{a=e.Wc.alpha.opacity||100}catch(c){}d=d>a?a:d}else{try{a=100*(b.getComputedStyle(e,s).opacity||1)}catch(f){}d*=a/100}e=e.parentNode}}catch(g){}return d||100},Yc:function(b){for(var e=this.s(b),b=this.ab(e),e=this.yb(e),d=100,a=0;this.oa(b);){a++;if(f.Da(b,b.parent))break;
else d=100,b.frameElement&&(d=this.yb(b.frameElement)),e*=d/100;b=b.parent}return e}}})});
H&&H("union/common/logic1430984032",[],function(){return{Vc:function(g){(g=g||"")&&(g=g.replace(/%u[\d|\w]{4}/g,function(f){return encodeURIComponent(unescape(f))}));return g},R:function(g,f){return g.replace(/{(.*?)}/g,function(e,g){return f[g]||""})},wc:function(g){var f="";window.JSON&&window.JSON.parse&&(f=window.JSON.parse(g));return f},Bb:function(g,f){if(g&&f){var e=g.match(RegExp("(^|&|\\?|#)"+f+"=([^&]*)(&|$)",""));if(e)return e[2]}return s},hd:function(g,f){var g=g||"",f=f||"?",e=arguments.callee;
e.hasOwnProperty[f]||(e[f]={});e=e[f];if(e.hasOwnProperty(g))return e[g];var h={},b=g.indexOf(f),i=g.substring(b+1).split("&");if(-1!==b)for(var b=0,d=i.length;b<d;b++){var a=i[b].split("="),c=decodeURIComponent(a[0]),a=decodeURIComponent(a[1]);h.hasOwnProperty(c)?(h[c].constructor!==Array&&(h[c]=[h[c]]),h[c].push(a)):h[c]=a}return e[g]=h}}});
H&&H("union/preview1430984032",["union/common/bom1430984032","union/common/logic1430984032","union/common/cookie1430984032"],function(g,f,e){function h(b){b=decodeURIComponent(b).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return f.wc(b)}function b(b,d){var a;a=d?d.substring(d.indexOf("?")):g.Da(window)?window.location.search.slice(1):window.top.location.search.slice(1);var c=document.referrer,j=0<=b.indexOf("inlay")||"ui"===b?"bd_cpro_prev":"bd_cpro_fprev",k="",o;try{o=document.cookie}catch(p){}-1!==
a.indexOf(j)&&(k=f.Bb(a,j));!k&&o&&-1!==o.indexOf(j)&&(k=e.V(j));!k&&-1!==c.indexOf(j)&&(k=f.Bb(c,j));return k}return{Za:function(e,d){var a=window.location.href,c=parseInt(e.rsi0,10),j=parseInt(e.rsi1,10),k=parseInt(e.at,10),o=u,p=b(d,a);if(p)if(p=h(p),k===l&&(k=1),1!==parseInt(p.type,10)&&2===(k&2))o=parseInt(p.imgWidth,10)===parseInt(c,10)&&parseInt(p.imgHeight,10)===parseInt(j,10);else if(1===parseInt(p.type,10)&&(1===(k&1)||64===(k&64)||32===(k&32)))o=n;return o?(c=0<=d.indexOf("inlay")||"ui"===
d?"bd_cpro_prev":"bd_cpro_fprev",a=b(d,a),j=e.tn,k=h(a),o=s,0<=d.indexOf("inlay")?o={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(k.type,10)?j+".html":2===parseInt(k.type,10)?"image.html":4===parseInt(k.type,10)?"flash.html":"blank_tips.html")+"?",paramString:(""+c+"=#"+a+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:0<=d.indexOf("float")&&(k=parseInt(k.type,10),k="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===k?"float_image.html":4===k?"float_flash.html":
"blank_tips.html")+"?",a="tn="+j+("&"+c+"="+a).replace(/\./g,"%252e")+"&ut="+ +new Date,o={serviceUrl:k,paramString:a}),o):s}}});
H&&H("union/business/businessLogic1430984032",["union/preview1430984032","union/common/dom1430984032","api"],function(g,f,e){var h={inlay:8,"float":2,patch:2,linkunit:20,popup:1},b={inlay:{},"float":{},patch:{},linkunit:{},popup:{}},i={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};return{qa:function(b){var a=
b._html||{},c="",f="http://cb.baidu.com/ecom?",h=b.id.split("_")[0],i=parseInt(a.conW||0,10)||parseInt(b._w,10)||parseInt(b.sw,10)||parseInt(a.rsi0,10),p=parseInt(a.conH||0,10)||parseInt(b._h,10)||parseInt(b.sh,10)||parseInt(a.rsi1,10),C=b.displayType,v=a.tn||"",w=v.toLowerCase(),B=a.ch||0,m=b.qn||"",r=a.n||"",t=a.dai||0;a.dtm="BAIDU_DUP2_SETJSONADSLOT";a.dc="2";a.di=h;a.ti=e.getDocumentTitle();(c=e.getInfo("timestampWathcer"+b.id))&&(a.tt=c.t1+"."+(c.t2-c.t1)+"."+(c.t3-c.t1)+"."+(+new Date-c.t1));
var c=[],q;for(q in a)q&&a.hasOwnProperty(q)&&c.push(""+q+"="+encodeURIComponent(a[q].toString()));c=c.join("&");if((q=g.Za(a,C))&&q.serviceUrl!==l&&q.paramString!==l)f=q.serviceUrl,c=q.paramString;return{slotId:h,slotWidth:i,slotHeight:p,displayType:C,styleType:w,iframeId:"cproIframe_"+h+"_"+a.dai,unionAccount:r,adIndex:t,channel:B,pvId:m,stuffType:"unknown",serviceUrl:f,paramString:c,delayIn:a.delayIn,delayOut:a.delayOut,sessionSync:a.sessionSync!==u&&"false"!==a.sessionSync,closeFor:a.closeFor,
xuantingType:a.xuanting,tn:v}},hb:function(b){var a={};a.$b=(b.$b||"pc").toLowerCase();a.C=(b.C||"inlay-fixed").toLowerCase();a.t=(b.t||"template_inlay_all_normal").toLowerCase();a.N=(b.N||"text").toLowerCase();a.K=b.K;if(-1<a.t.indexOf("tlink")||-1<a.t.indexOf("linkunit"))a.C="linkunit-fixed";0<=a.t.indexOf("float_xuanfuwin")&&(a.C="popup-float");b=a.C.split("-");a.Sa=b[0]||"inlay";a.Uc=b[1]||"fixed";return a},Aa:function(b){var b=this.hb(b),a=b.Sa;return this.gc(b)<h[a]},gc:function(d){var d=this.hb(d),
a=0,d=b[d.Sa],c;for(c in d)c&&d[c]&&d.hasOwnProperty(c)&&(f.m(c)?a++:d[c]=l);return a},sa:function(d){d=this.hb(d);b[d.Sa][d.K]=1;return n},Ba:function(b,a){var c=document.getElementById("cpro_"+b);c||(c=document.getElementById(a));return c},jc:function(b){return i[b]},Ha:function(b){var a=b.slotId;E(["viewWatch"],function(c){c.register({id:a,wrapperId:b.iframeId,logType:"block",extra:"ch="+b.channel+"&jk="+b.pvId+"&n="+b.unionAccount})},n)}}});H&&H("union/floatad","union/common/oo1430984032,union/common/cookie1430984032,union/common/dom1430984032,union/common/bom1430984032,union/common/logic1430984032,union/business/businessLogic1430984032,union/preview1430984032,api".split(","),function(g,f,e,h,b,i,d,a){function c(c,b,k){if(!c||!c._html)return s;var e=i.jc(b),j=c._html,f="",g="http://cb.baidu.com/ecom?",h=c.id.split("_")[0],t=parseInt(j.conW||0,10)||parseInt(j.rsi0,10)||parseInt(c._w,10)||parseInt(c.sw,10),q=parseInt(j.conH||0,10)||parseInt(j.rsi1,10)||parseInt(c._h,10)||parseInt(c.sh,10),f=j.tn||"",z=f.toLowerCase(),
A=j.n||"",F=parseInt(j.ch||0,10),x=parseInt(j.dai||0,10);j.dtm="BAIDU_DUP2_SETJSONADSLOT";j.dc="2";j.di=h;j.distp=b;j.ti=a.getDocumentTitle();(c=a.getInfo("timestampWathcer"+c.id))&&(j.tt=c.t1+"."+(c.t2-c.t1)+"."+(c.t3-c.t1)+"."+(+new Date-c.t1));0<=f.indexOf("float")&&(j.tn="template_float_all_normal");var c=[],y;for(y in j)y&&j.hasOwnProperty(y)&&c.push(""+y+"="+encodeURIComponent(j[y].toString()));f=c.join("&");if((y=d.Za(j,e))&&y.serviceUrl!==l&&y.paramString!==l)g=y.serviceUrl,f=y.paramString;
return{e:h,Kb:t,Jb:q,C:e,Wa:parseInt(j.rsi6,10),Va:parseInt(j.rsi7,10),Ra:parseInt(j.ccw,10),Qa:parseInt(j.ct,10),ma:parseInt(j.pt,10),ba:k,F:parseInt(j.fa,10),fc:parseInt(j.flw,10),nd:j.tn,Fa:j.qn,t:z,L:g,H:f,b:"cproIframe"+(b||parseInt(100+100*Math.random(),10)),ha:A,$:F,za:x,N:"unknown"}}function j(c){var a=c.e;E(["viewWatch"],function(b){b.register({id:a,wrapperId:c.b,logType:"block",extra:"ch="+c.$+"&jk="+c.Fa+"&n="+c.ha})},n)}var k;g(function(c){k=c.Ma({ec:{1:{rb:1,qb:150},2:{rb:0,qb:40},3:{rb:0,
qb:0}},constructor:function(a){this.b=a.b;this.L=a.L;this.H=a.H;this.K=this.b+"holder";this.F=a.F;this.ba=a.ba;this.ma=a.ma;this.xb=a.fc;this.P=a.Kb;this.Y=a.Jb;this.Oa=a.Kb;this.Na=a.Jb;this.Fa=a.Fa;this.Wa=a.Wa;this.Va=a.Va;this.Ra=a.Ra;this.Y+=20;this.ub=1===this.F?0:5;this.P+=10;this.Y+=10;this.Mb=this.ec;this.Qa=a.Qa;this.e=a.e;this.B=h.B();e.bind(window,"resize",c.i(this.M,this));e.bind(window,"scroll",c.i(this.M,this))},jb:function(){var a=document.createElement("div");a.style.cssText=["box-sizing: content-box;maring:0;padding:0;display:block;visibility:visible;border:none;background:none;float:none;overflow:hidden;position:absolute;",
"z-index:"+(1===this.F?2147483646:2147483647)+";","width:"+this.P+"px;","height:"+(this.Y+this.ub)+"px"].join("");a.id=this.K;var d="",k=document.createElement("div");k.id=this.b+"CloseBtnWrap";var e=document.createElement("div");e.id=this.b+"CloseBtn";1===this.F?(k.style.cssText=["box-sizing: content-box;position:absolute;top:275px;left:0;cursor:pointer;","width:"+this.P+"px;","height:28px;z-index:100;opacity:0;filter:alpha(opacity=0);background-color:#999999;"].join(""),e.style.cssText=["box-sizing: content-box;position:absolute;",
"width:"+this.P+"px;","height:20px;top:280px;left:0;cursor:pointer;background-color:#999999;color:#fff;font-size:12px;font-family: \u5fae\u8f6f\u96c5\u9ed1;text-align:center;line-height:20px;"].join(""),e.innerHTML="\u5173\u95ed"):(k.style.cssText=["box-sizing: content-box;position:absolute;top:0px;","left:"+(this.P-61)+"px;","cursor:pointer;width:61px;height:20px;z-index:100;opacity:0;filter:alpha(opacity=0);background-color:#999999;margin:0;paddong:0;"].join(""),e.style.cssText=["box-sizing: content-box;position:absolute;width:61px;height:20px;top:0;",
"left:"+(this.P-61)+"px;","margin:0;padding:0;margin-bottom:5px;cursor:pointer;overflow:hidden;"].join(""),e.innerHTML='<div style="box-sizing: content-box;width:40px;height:20px;background-color:#999999;color:#fff;float:left;margin-right:1px;font-size:12px;font-family:\u5fae\u8f6f\u96c5\u9ed1;text-align: center;line-height:20px;">\u5173\u95ed</div><a style="maring:0;padding:0;display:inline-block;border:none;overflow:hidden;height:20px;line-height:20px;cursor:pointer;width:20px;background:url(\'http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.1/xuanfu_close.png\') no-repeat 0 0;margin-bottom:3px;float:left" ></a>',
d="position:absolute;left:0;top:25px;");a.appendChild(k);a.appendChild(e);e=document.createElement("div");d=["box-sizing: content-box;","width:"+this.Oa+"px;","height:"+this.Na+"px;","overflow:hidden;"+d];d.push("padding:4px;");d.push("border:#acacac 1px solid;");e.style.cssText=d.join("");this.H+="&adclass=1&conW="+this.Oa+"&conH="+this.Na;e.innerHTML=b.R('<div style="display:none">-</div><iframe id="{iframeId}" src="{cproServiceUrl}{paramString}" width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true"></iframe></div>',
{iframeId:this.b,cproServiceUrl:this.L,paramString:this.H,iframeWidth:this.Oa,iframeHeight:this.Na});a.appendChild(e);this.ea(a);for(var d=document.body.children,e=d.length,j=10>d.length?d.length:10,i=document.body.lastChild,f=0;f<j;f++){var g=d[e-f-1].getAttribute("data-baidu-dan-id");if(g||""===g){i=d[e-f-1];break}}i.parentNode.insertBefore(a,i);k.onclick=c.i(this.Tb,this);k.onmouseover=c.i(this.Vb,this);k.onmouseout=c.i(this.Ub,this)},lc:function(){var c=2;return c=1===this.xb?this.B?1===this.ma?
4:3:1===this.ma?2:1:1===this.ma?6:5},kc:function(){var c=this.Va;return c=0>c||9999<c?0:Math.floor(c)},mc:function(){var c=this.Wa;return c=0>c||9999<c?this.Mb[this.F].qb:Math.floor(c)},ic:function(){var c=this.Ra;4095<c&&(c=4095);return c=Math.floor(c)},M:function(){this.ta&&clearTimeout(this.ta);this.ta=setTimeout(c.i(this.Fc,this),50)},Fc:function(){var c=document.getElementById(this.K);c&&this.ea(c)},ea:function(c){c.style.position=this.B?(1===this.F||2===this.F)&&2===this.xb?"absolute":"fixed":
"absolute";var a=h.G(window),b=h.$a(window),d=h.D(window),k=h.o(window),j=this.P,o=this.Y+this.ub,i=this.Mb[this.F].rb,f=e.u(document.body,"position").toString(),g=e.u(document.body,"width").toString().replace("px",""),A=this.lc(),F="right",x,y,D=this.kc(),G=this.mc();x=this.ic();var I=e.pc(document.body).left;x=Math.floor((d-x)/2)-j-10;x=0<=x&&0==A%2?x:7;switch(A){case 1:case 2:"relative"===f&&"auto"!=g&&d>g?(j=d-x-j-I,b=b+x-I):(j=b+d-x-j,b+=x);F="left";y=Math.max(1===i?k>=o+G?a+G:a+k-o:k>=o+G?a+
k-G-o:a,D);break;case 3:case 4:b=j=x;1===i?y=Math.max(k>=o+G?G:k-o,D-a):(y=Math.min(a+k-D-o,G),y=Math.min(y,k-o));break;case 5:case 6:"relative"===f&&"auto"!=g&&d>g?(j=d-(d-g)/2-x-j,b=b+x-(d-g)/2):(j=b+d-x-j,b+=x);F="left";y=Math.max(1===i?G:k>=o+G?k-G-o:0,D);break;default:b=j=10}if(1===A%4||2===A%4)i=1;a=i?"top":"bottom";1===(this.ba&1)?(c=c.style,c.left=b+"px",c[a]=y+"px",c.visibility="visible"):2===(this.ba&2)&&(c=c.style,c[F]=j+"px",c[a]=y+"px",c.visibility="visible")},Tb:function(){var c=document.getElementById(this.K);
if(2===this.Qa){var a="bd_close_"+this.e,d=f.V(a,window),d=d?d|this.ba:this.ba;f.ga(a,d,{path:"/"})}c.parentNode&&c.parentNode.removeChild?c.parentNode.removeChild(c):document.body.removeChild(c);c={jk:this.Fa||"",dt:(new Date).getTime(),rnd:Math.floor(2147483648*Math.random())};try{h.Ec(b.R("http://eclick.baidu.com/fcb.jpg?jk={jk}&dt={dt}&rnd={rnd}",c),window)}catch(k){}},Vb:function(){var c=document.getElementById(this.b+"CloseBtn");c&&(1===this.F?c.style.backgroundColor="#0066cc":(c.getElementsByTagName("div")[0].style.backgroundColor=
"#0066cc",c.getElementsByTagName("a")[0].style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.0/xuanfu_mouseover_close.png)"))},Ub:function(){var c=document.getElementById(this.b+"CloseBtn");c&&(1===this.F?c.style.backgroundColor="#999999":(c.getElementsByTagName("div")[0].style.backgroundColor="#999999",c.getElementsByTagName("a")[0].style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.1/xuanfu_close.png)"))}})});return{render:function(a){var d;
if(h.oa())d=u;else if(d=parseInt(a._html.ww||0,10),4095<d&&(d=4095),d>=screen.width)d=u;else{var b=d=u;d=/iphone|ipod|android|blackberry|opera mini|opera mobi|skyfire|maemo|windows phone|palm|iemobile|symbian|symbianos|fennec/i.test(navigator.userAgent.toLowerCase());b=/ipad|android 3|sch-i800|playbook|tablet|kindle|gt-p1000|sgh-t849|shw-m180s|a510|a511|a100|dell streak|silk|SAMSUNG.*Tablet|Galaxy.*Tab|SC-01C|GT-P1000|GT-P1003|GT-P1010|GT-P3105|GT-P6210|GT-P6800|GT-P6810|GT-P7100|GT-P7300|GT-P7310|GT-P7500|GT-P7510|SCH-I800|SCH-I815|SCH-I905|SGH-I957|SGH-I987|SGH-T849|SGH-T859|SGH-T869|SPH-P100|GT-P3100|GT-P3108|GT-P3110|GT-P5100|GT-P5110|GT-P6200|GT-P7320|GT-P7511|GT-N8000|GT-P8510|SGH-I497|SPH-P500|SGH-T779|SCH-I705|SCH-I915|GT-N8013|GT-P3113|GT-P5113|GT-P8110|GT-N8010|GT-N8005|GT-N8020|GT-P1013|GT-P6201|GT-P7501|GT-N5100|GT-N5110|SHV-E140K|SHV-E140L|SHV-E140S|SHV-E150S|SHV-E230K|SHV-E230L|SHV-E230S|SHW-M180K|SHW-M180L|SHW-M180S|SHW-M180W|SHW-M300W|SHW-M305W|SHW-M380K|SHW-M380S|SHW-M380W|SHW-M430W|SHW-M480K|SHW-M480S|SHW-M480W|SHW-M485W|SHW-M486W|SHW-M500W|GT-I9228|SCH-P739|SCH-I925|GT-I9200|GT-I9205|GT-P5200|GT-P5210|SM-T311|SM-T310|SM-T210|SM-T211|SM-P900|IdeaTab|S2110|S6000|K3011|A3000|A1000|A2107|A2109|A1107/i.test(navigator.userAgent.toLowerCase());
d=1024>screen.width&&d&&!b?u:n}if(d){if(a&&a._html){var e=a._html;d=parseInt(e.fa,10);var b=parseInt(e.ls,10),g=a.id.split("_")[0],B=0;2===parseInt(e.ct,10)&&(B=parseInt(f.V("bd_close_"+g),10));e=[];1===d||2===d?(2===(b&2)&&2!==(B&2)&&e.push(c(a,"2002",2)),1===(b&1)&&1!==(B&1)&&e.push(c(a,"2001",1))):(b=3!==b?b:2,B!=b&&e.push(c(a,1===b?"2003":"2004",b)));a=e}else a=l;d=a.length;for(b=0;b<d;b++)if(B=a[b])e={C:B.C,t:B.t,N:B.N,K:B.b},i.Aa(e)&&((new k(B)).jb(),i.sa(e),j(B))}}}});
})();