/*! ver:1430984032 Copyright 2015 Baidu Inc. All Rights Reserved. */;(function(){var l=void 0,n=!0,s=null,u=!1,E=window.BAIDU_DUP_require,H=window.BAIDU_DUP_define;
H&&H("union/common/cookie1430984032",[],function(){return{V:function(g,f){var e,h=RegExp("(^| )"+g+"=([^;]*)(;|$)").exec((f||window).document.cookie);h&&(e=h[2]);return e},ga:function(g,f,e){var e=e||{},h=e.aa;"number"==typeof e.aa&&(h=new Date,h.setTime(h.getTime()+e.aa));document.cookie=""+g+"="+f+(e.path?"; path="+e.path:"")+(h?"; expires="+h.toGMTString():"")+(e.domain?"; domain="+e.domain:"")+(e.ld?"; secure":"")},remove:function(g){var f=new Date;f.setTime(f.getTime()-86400);this.ga(g,"",{path:"/",aa:f})}}});
H&&H("union/common/bom1430984032",[],function(){var g={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(g.g=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Xc=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(g.kd=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Tc=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.ed)&&
(g.fd=+RegExp.$1)}catch(f){}g.Fb=/webkit/i.test(navigator.userAgent);g.uc=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);g.Db="CSS1Compat"==document.compatMode;return{h:g,B:function(){var e=n;if(this.h.g&&(7>this.h.g||"BackCompat"===document.compatMode))e=u;return e},$c:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.scrollWidth:e.document.documentElement.scrollWidth}catch(f){return 0}},Zc:function(e){try{return e=e||window,"BackCompat"===
e.document.compatMode?e.document.body.scrollHeight:e.document.documentElement.scrollHeight}catch(f){return 0}},D:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientWidth:e.document.documentElement.clientWidth}catch(f){return 0}},o:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientHeight:e.document.documentElement.clientHeight}catch(f){return 0}},G:function(e){e=(e||window).document;return window.pageYOffset||e.documentElement.scrollTop||
e.body.scrollTop},$a:function(e){e=(e||window).document;return window.pageXOffset||e.documentElement.scrollLeft||e.body.scrollLeft},Gb:function(e){var f=u;try{e&&"object"===typeof e&&e.document&&"setInterval"in e&&(f=n)}catch(b){f=u}return f},oa:function(e){e=e||window;return e!=window.top&&e!=e.parent||!this.Gb(e)},Da:function(e,f){for(var f=2===arguments.length?f:e.parent,b=0;10>b++&&this.oa(e,f);){var i;try{i=!!e.parent.location.toString()}catch(d){i=u}if(!i)return n;e=e.parent}return 10<=b?n:
u},Ec:function(e,f){var b=new Image,i="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),f=f||window;f[i]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=s;b=f[i]=s};b.src=e},Ya:function(e){if(!e)return document;"string"===typeof e&&(e=document.getElementById(e));return 9===e.nodeType?e:e.ownerDocument||e.document},ab:function(e){"string"===typeof e&&(e=document.getElementById(e));e=this.Ya(e);return e.parentWindow||e.defaultView||s},bd:function(e){e=e||window;return this.oa(e)&&
!this.Da(e,e.top)&&this.Gb(e.top)?e.top:e}}});
H&&H("union/common/oo1430984032",[],function(){function g(b){var e=g.create(g);return b.call(e,e,e.sb)}function f(b,e){if(b.constructor===Array)for(var d=0,a=b.length;d<a;d++){if(e.call(b,b[d],d,b)===u)return u}else{var d=!{toString:1}.propertyIsEnumerable("toString"),c="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(a in b)if(b.hasOwnProperty(a)&&e.call(b,b[a],a,b)===u)return u;if(d){d=0;for(a=c.length;d<a;d++){var f=c[d];if(b.hasOwnProperty(f)&&
e.call(b,f,d,b)===u)return u}}}return n}function e(b,e,d){f(e,function(a,c){if(!b.hasOwnProperty(c)||d)b[c]=a})}function h(b){function e(){}if(Object.create)return Object.create(b);e.prototype=b;return new e}g.sb={};g.create=h;g.bc=f;g.Ma=function(b){var f,d=b.hasOwnProperty("constructor")?b.constructor:function(){};d.prototype=b;d.prototype.constructor=d;f=f||{};f.kb&&e(d,f.kb);return d};g.extend=function(b,f,d){var a;a=f.hasOwnProperty("constructor")?f.constructor:function(){b.constructor.apply(this,
arguments)};a.prototype=h(b.prototype);e(a.prototype,f,n);a.prototype.constructor=a;a.prototype.Qc=b.prototype;e(a,b);d=d||{};d.kb&&e(a,d.kb,n);return a};g.gd=function(b){var e=this.sb;f(b.split("."),function(b){e.hasOwnProperty(b)||(e[b]={});e=e[b]});return e};g.i=function(b,e){var d;return function(){d=d||[];for(var a=0,c=arguments.length;a<c;a++)d.push(arguments[a]);return b.apply(e||{},d)}};return g});
H&&H("union/common/dom1430984032",["union/common/oo1430984032","union/common/bom1430984032"],function(g,f){return g(function(e){var g=f.h;return{m:function(b,e){return"string"===typeof b||b instanceof String?(e||window).document.getElementById(b):b},Cb:function(b,i){var d=n;if("string"===typeof i)return b.id===i;if(i.constructor===Object)return e.bc(i,function(a,c){var e=(b.getAttribute?b.getAttribute(c):b[c])||b[c];if("tagName"===c){if(e.toUpperCase()!=a.toUpperCase())return d=u}else if(e!=a)return d=u}),d;if(i.constructor===
Array){var a=i.concat([]);a.reverse();for(var c=b;c&&a.length;c=c.parentNode)this.Cb(c,a[0])&&a.shift();return!a.length?n:u}},Ob:function(b,e){if(b&&e(b)!==u){var d=b.childNodes;if(d)for(var a=0,c=d.length;a<c;a++)if(this.Ob(d[a],e)===u)return u}},Lb:function(b,e){var d=this;b.constructor===Object&&(b=this.s(b));if("string"===typeof e){for(var a=document.getElementById(e),c=a;c;){if(c===b)return a;c=c.parentNode}return s}if(e.constructor===Object){var f=s;d.Ob(b,function(a){if(d.Cb(a,e))return f=
a,u});return f}},s:function(b){if(b){if(b.nodeName)return b;1<arguments.length&&(b=Array.prototype.slice.call(arguments,0));if("string"===typeof b)return document.getElementById(b);if(b.constructor===Object)return this.Lb(document.documentElement,b);if(b.constructor===Array){for(var e=b.concat([]),d=document.documentElement;e.length&&d;)d=this.Lb(d,e.shift());return d}}},Cc:function(b,i,d){var d=d||this.pd||window,a=d.document;this.wb=0;this.da=this.da||[];this.da.push({Xa:b,vb:i||0,Ta:u});var c=
e.i(function(){var c=u;this.wb++;var b=u;try{d.frameElement&&(b=n)}catch(e){b=n}if(g.g&&9>g.g&&!b)try{a.documentElement.doScroll("left"),c=n}catch(i){}else if("complete"===a.readyState||this.ac)c=n;else if(3E5<this.wb){this.U&&(d.clearInterval(this.U),this.U=s);return}if(c)try{if(this.da&&this.da.length)for(var c=0,f=this.da.length;c<f;c++){var v=this.da[c];v&&v.Xa&&!v.Ta&&(v.vb?(v.Ta=n,d.setTimeout(v.Xa,v.vb)):(v.Ta=n,v.Xa()))}}catch(w){throw w;}finally{this.U&&(d.clearInterval(this.U),this.U=s)}},
this),b=e.i(function(){this.ac=n;c()},this);this.U||(this.U=d.setInterval(c,50),a.addEventListener?(a.addEventListener("DOMContentLoaded",b,u),d.addEventListener("load",b,u)):a.attachEvent&&d.attachEvent("onload",b,u))},B:function(){var b=n;if(g.g&&(7>g.g||"BackCompat"===document.compatMode))b=u;return b},bind:function(b,e,d){"string"===typeof b&&(b=this.s(b));e=e.replace(/^on/i,"").toLowerCase();b.addEventListener?b.addEventListener(e,d,u):b.attachEvent&&b.attachEvent("on"+e,d);return b},Pb:function(b,
e,d){b=this.s(b);if(!b)return s;e=e.replace(/^on/i,"").toLowerCase();b.removeEventListener?b.removeEventListener(e,d,u):b.detachEvent&&b.detachEvent("on"+e,d);return b},u:function(b,e){var d;"string"===typeof b&&(b=this.s(b));var a=f.Ya(b),c="",c=-1<e.indexOf("-")?e.replace(/[-_][^-_]{1}/g,function(a){return a.charAt(1).toUpperCase()}):e.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()});a&&a.defaultView&&a.defaultView.getComputedStyle?((a=a.defaultView.getComputedStyle(b,s))&&
(d=a.getPropertyValue(e)),"boolean"!==typeof d&&!d&&(d=a.getPropertyValue(c))):b.currentStyle&&((a=b.currentStyle)&&(d=a[e]),"boolean"!==typeof d&&!d&&(d=a[c]));return d},pc:function(b,e){e=e||window;"string"===typeof b&&(b=this.s(b));if(b){for(var d=this.ca(b),a,c=0;e!=e.parent&&10>c;)c++,a=this.ca(e.frameElement),d.left+=a.left,d.top+=a.top,e=e.parent;return d}},ca:function(b){"string"===typeof b&&(b=this.s(b));var e=f.Ya(b),d=f.h;0<d.uc&&e.getBoxObjectFor&&this.u(b,"position");var a={left:0,top:0},
c;if(b==(d.g&&!d.Db?e.body:e.documentElement)||!b)return a;if(b.getBoundingClientRect)b=b.getBoundingClientRect(),a.left=Math.floor(b.left)+Math.max(e.documentElement.scrollLeft,e.body.scrollLeft),a.top=Math.floor(b.top)+Math.max(e.documentElement.scrollTop,e.body.scrollTop),a.left-=e.documentElement.clientLeft,a.top-=e.documentElement.clientTop,b=e.body,e=parseInt(this.u(b,"borderLeftWidth"),10),b=parseInt(this.u(b,"borderTopWidth"),10),d.g&&!d.Db&&(a.left-=isNaN(e)?2:e,a.top-=isNaN(b)?2:b);else{c=
b;do{a.left+=c.offsetLeft;a.top+=c.offsetTop;if(0<d.Fb&&"fixed"==this.u(c,"position")){a.left+=e.body.scrollLeft;a.top+=e.body.scrollTop;break}c=c.offsetParent}while(c&&c!=b);if(0<d.opera||0<d.Fb&&"absolute"==this.u(b,"position"))a.top-=e.body.offsetTop;for(c=b.offsetParent;c&&c!=e.body;){a.left-=c.scrollLeft;if(!d.opera||"TR"!=c.tagName)a.top-=c.scrollTop;c=c.offsetParent}}return a},Ab:function(b,e){var b=this.s(b),d=b.offsetWidth;if(e||u)var a=this.u(b,"marginLeft").toString().toLowerCase().replace("px",
"").replace("auto","0"),c=this.u(b,"marginRight").toString().toLowerCase().replace("px","").replace("auto","0"),d=d+(parseInt(a||0,10)+parseInt(c||0,10));return d},zb:function(b,e){var b=this.s(b),d=b.offsetHeight;if(e||u)var a=this.u(b,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),c=this.u(b,"marginBottom").toString().toLowerCase().replace("px","").replace("auto","0"),d=d+(parseInt(a||0,10)+parseInt(c||0,10));return d},ad:function(b){var b=this.s(b),e=this.ab(b),d=0;
if(this.oa(window)&&!f.Da(window)){for(;e.parent!=window.top&&10>d;)d++,e=e.parent;10>d&&(b=e.frameElement||b)}return b},yb:function(b){var e=this.s(b),b=this.ab(e),d=100,a;try{for(;e&&e.tagName;){a=100;if(this.h.g){if(5<this.h.g)try{a=e.Wc.alpha.opacity||100}catch(c){}d=d>a?a:d}else{try{a=100*(b.getComputedStyle(e,s).opacity||1)}catch(f){}d*=a/100}e=e.parentNode}}catch(g){}return d||100},Yc:function(b){for(var e=this.s(b),b=this.ab(e),e=this.yb(e),d=100,a=0;this.oa(b);){a++;if(f.Da(b,b.parent))break;
else d=100,b.frameElement&&(d=this.yb(b.frameElement)),e*=d/100;b=b.parent}return e}}})});
H&&H("union/common/logic1430984032",[],function(){return{Vc:function(g){(g=g||"")&&(g=g.replace(/%u[\d|\w]{4}/g,function(f){return encodeURIComponent(unescape(f))}));return g},R:function(g,f){return g.replace(/{(.*?)}/g,function(e,g){return f[g]||""})},wc:function(g){var f="";window.JSON&&window.JSON.parse&&(f=window.JSON.parse(g));return f},Bb:function(g,f){if(g&&f){var e=g.match(RegExp("(^|&|\\?|#)"+f+"=([^&]*)(&|$)",""));if(e)return e[2]}return s},hd:function(g,f){var g=g||"",f=f||"?",e=arguments.callee;
e.hasOwnProperty[f]||(e[f]={});e=e[f];if(e.hasOwnProperty(g))return e[g];var h={},b=g.indexOf(f),i=g.substring(b+1).split("&");if(-1!==b)for(var b=0,d=i.length;b<d;b++){var a=i[b].split("="),c=decodeURIComponent(a[0]),a=decodeURIComponent(a[1]);h.hasOwnProperty(c)?(h[c].constructor!==Array&&(h[c]=[h[c]]),h[c].push(a)):h[c]=a}return e[g]=h}}});
H&&H("union/preview1430984032",["union/common/bom1430984032","union/common/logic1430984032","union/common/cookie1430984032"],function(g,f,e){function h(b){b=decodeURIComponent(b).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return f.wc(b)}function b(b,d){var a;a=d?d.substring(d.indexOf("?")):g.Da(window)?window.location.search.slice(1):window.top.location.search.slice(1);var c=document.referrer,j=0<=b.indexOf("inlay")||"ui"===b?"bd_cpro_prev":"bd_cpro_fprev",k="",o;try{o=document.cookie}catch(p){}-1!==
a.indexOf(j)&&(k=f.Bb(a,j));!k&&o&&-1!==o.indexOf(j)&&(k=e.V(j));!k&&-1!==c.indexOf(j)&&(k=f.Bb(c,j));return k}return{Za:function(e,d){var a=window.location.href,c=parseInt(e.rsi0,10),j=parseInt(e.rsi1,10),k=parseInt(e.at,10),o=u,p=b(d,a);if(p)if(p=h(p),k===l&&(k=1),1!==parseInt(p.type,10)&&2===(k&2))o=parseInt(p.imgWidth,10)===parseInt(c,10)&&parseInt(p.imgHeight,10)===parseInt(j,10);else if(1===parseInt(p.type,10)&&(1===(k&1)||64===(k&64)||32===(k&32)))o=n;return o?(c=0<=d.indexOf("inlay")||"ui"===
d?"bd_cpro_prev":"bd_cpro_fprev",a=b(d,a),j=e.tn,k=h(a),o=s,0<=d.indexOf("inlay")?o={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(k.type,10)?j+".html":2===parseInt(k.type,10)?"image.html":4===parseInt(k.type,10)?"flash.html":"blank_tips.html")+"?",paramString:(""+c+"=#"+a+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:0<=d.indexOf("float")&&(k=parseInt(k.type,10),k="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===k?"float_image.html":4===k?"float_flash.html":
"blank_tips.html")+"?",a="tn="+j+("&"+c+"="+a).replace(/\./g,"%252e")+"&ut="+ +new Date,o={serviceUrl:k,paramString:a}),o):s}}});
H&&H("union/business/businessLogic1430984032",["union/preview1430984032","union/common/dom1430984032","api"],function(g,f,e){var h={inlay:8,"float":2,patch:2,linkunit:20,popup:1},b={inlay:{},"float":{},patch:{},linkunit:{},popup:{}},i={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};return{qa:function(b){var a=
b._html||{},c="",f="http://cb.baidu.com/ecom?",h=b.id.split("_")[0],i=parseInt(a.conW||0,10)||parseInt(b._w,10)||parseInt(b.sw,10)||parseInt(a.rsi0,10),p=parseInt(a.conH||0,10)||parseInt(b._h,10)||parseInt(b.sh,10)||parseInt(a.rsi1,10),C=b.displayType,v=a.tn||"",w=v.toLowerCase(),B=a.ch||0,m=b.qn||"",r=a.n||"",t=a.dai||0;a.dtm="BAIDU_DUP2_SETJSONADSLOT";a.dc="2";a.di=h;a.ti=e.getDocumentTitle();(c=e.getInfo("timestampWathcer"+b.id))&&(a.tt=c.t1+"."+(c.t2-c.t1)+"."+(c.t3-c.t1)+"."+(+new Date-c.t1));
var c=[],q;for(q in a)q&&a.hasOwnProperty(q)&&c.push(""+q+"="+encodeURIComponent(a[q].toString()));c=c.join("&");if((q=g.Za(a,C))&&q.serviceUrl!==l&&q.paramString!==l)f=q.serviceUrl,c=q.paramString;return{slotId:h,slotWidth:i,slotHeight:p,displayType:C,styleType:w,iframeId:"cproIframe_"+h+"_"+a.dai,unionAccount:r,adIndex:t,channel:B,pvId:m,stuffType:"unknown",serviceUrl:f,paramString:c,delayIn:a.delayIn,delayOut:a.delayOut,sessionSync:a.sessionSync!==u&&"false"!==a.sessionSync,closeFor:a.closeFor,
xuantingType:a.xuanting,tn:v}},hb:function(b){var a={};a.$b=(b.$b||"pc").toLowerCase();a.C=(b.C||"inlay-fixed").toLowerCase();a.t=(b.t||"template_inlay_all_normal").toLowerCase();a.N=(b.N||"text").toLowerCase();a.K=b.K;if(-1<a.t.indexOf("tlink")||-1<a.t.indexOf("linkunit"))a.C="linkunit-fixed";0<=a.t.indexOf("float_xuanfuwin")&&(a.C="popup-float");b=a.C.split("-");a.Sa=b[0]||"inlay";a.Uc=b[1]||"fixed";return a},Aa:function(b){var b=this.hb(b),a=b.Sa;return this.gc(b)<h[a]},gc:function(d){var d=this.hb(d),
a=0,d=b[d.Sa],c;for(c in d)c&&d[c]&&d.hasOwnProperty(c)&&(f.m(c)?a++:d[c]=l);return a},sa:function(d){d=this.hb(d);b[d.Sa][d.K]=1;return n},Ba:function(b,a){var c=document.getElementById("cpro_"+b);c||(c=document.getElementById(a));return c},jc:function(b){return i[b]},Ha:function(b){var a=b.slotId;E(["viewWatch"],function(c){c.register({id:a,wrapperId:b.iframeId,logType:"block",extra:"ch="+b.channel+"&jk="+b.pvId+"&n="+b.unionAccount})},n)}}});H&&H("union/xuanting","union/common/cookie1430984032,union/common/bom1430984032,union/common/dom1430984032,union/common/logic1430984032,union/common/oo1430984032,union/business/businessLogic1430984032".split(","),function(g,f,e,h,b,i){var d;b(function(a){d=a.Ma({constructor:function(c){var a=c.xa.id;this.xa=e.s(c.xa);this.type=+c.type;this.src=c.src;this.width=c.width;this.height=c.height;this.t=c.t||"";this.lb=c.lb||"";this.$=c.$||"0";this.ha=c.ha||"";this.ra=c.ra||"";this.I=this.ob=5;this.H=c.H;this.L=c.L;this.e=c.e;this.J="bd_close_"+this.e;this.Kc=!!g.V(this.J);
this.b=this.nc(this.e);this.r=a;this.d="";this.fileName="c";this.za=c.za||0;this.backgroundColor=c.backgroundColor;this.ka=c.ka;2===this.type?this.d="top":3===this.type&&(this.d="bottom");this.d&&(this.wa=n,this.w=+c.w||0,this.z=+c.z||0,this.v=!!c.v||u,this.j=+c.j||0,this.Pa=500);this.Q=c.Q||u},cd:function(c){return"string"===typeof c?document.getElementById(c):c},Hc:function(c,a){return(a||document).getElementsByTagName(c)[0]},Nb:function(c,a){return c.replace(/\{(.*?)\}/g,function(c,d){return a.hasOwnProperty(d)?
a[d]:c})},nc:function(c){return"cproIframe_"+c},h:f.h,Ga:function(){var c={path:""};if(this.j&&!this.v){var a=new Date;a.setTime(a.getTime()+this.j);c.aa=a}g.ga(this.J,1,c)},Dc:function(c){var a=new Date;a.setTime(a.getTime()-86400);g.ga(c,"",{path:"/",aa:a})},M:function(){this.clientWidth=f.D(window);this.clientHeight=f.o(window);this.d&&(this.q&&(this.q.style.width=this.clientWidth+"px"),this.S&&(this.S.style.width=this.clientWidth+"px"));this.ta&&clearTimeout(this.ta);this.ta=setTimeout(a.i(this.pa,
this),5)},pa:function(){var c=this.q;if(c)if(e.B()){if(c.style.zIndex=2147483646,1===this.type)if("fixed"==c.style.position)this.ja(),this.Sb()&&(c.style.cssText=s,this.ib());else{var a=this.pb();a&&(this.la(),c.style.position="fixed",c.style.top=a+"px",this.ja())}}else this.ea(this.q)},Sb:function(c){var a;c?(a=document.getElementById(c),c=document.getElementById(""+c+"placeholder")):(a=this.q||document.getElementById(this.r),c=document.getElementById(""+this.r+"placeholder"));return a&&c&&(c=this.k(c).Ja,
this.k(a).Ja<=c)?n:u},ja:function(c){var a;c?(a=document.getElementById(c),c=document.getElementById(""+c+"placeholder")):(a=this.q||document.getElementById(this.r),c=document.getElementById(""+this.r+"placeholder"));a&&c&&(c=this.k(c).left,a.style.left=c+"px")},k:function(c){var a=e.ca(c),d=f.$a(window),b=f.G(window),i=e.Ab(c,u),c=e.zb(c,u);return{top:a.top-b,bottom:a.top-b+c,left:a.left-d,right:a.left-d+i,Ja:a.top,Sc:a.top+c,Ea:a.left,jd:a.left+i}},ea:function(){this.clientWidth=f.D(window);this.clientHeight=
f.o(window);var c=f.G(window),a=e.u(document.body,"position").toString(),d=e.ca(document.body),b=d.left,i=d.top;if(d=this.q)if(d.style.position="absolute",d.style.zIndex=2147483646,1===this.type)if(document.getElementById(""+this.r+"placeholder")){var g=document.getElementById(""+this.r+"placeholder"),h=this.k(g);d.style.top=""+(c+this.I)+"px";d.style.left=""+h.Ea+"px";"relative"==a&&(d.style.top=c+this.I-i+"px",d.style.left=h.Ea-b+"px");d.style.visibility="visible";c=this.k(d);h.Ja>=c.Ja&&(d.parentNode.removeChild(d),
g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),d.style.cssText=s)}else{if(g=this.Ic(this.r))this.I=g,this.la(this.r),g=document.getElementById(""+this.r+"placeholder"),h=this.k(g),d.parentNode.removeChild(d),document.body.appendChild(d),d.style.zIndex=2147483646,d.style.top=c+this.I+"px",d.style.left=h.Ea+"px","relative"==a&&(d.style.top=c+this.I-i+"px",d.style.left=h.Ea-b+"px"),d.style.visibility="visible",d.style.position="absolute"}else 2===this.type?d.style.top=c+"px":3===this.type&&
(d.style.top=c+this.clientHeight-(this.height+10)+"px")},jb:function(){if(!this.Q){var c=this.type,a=this.width,d=this.height,b={srcAttrName:c===l||1==c?"src":"_src",iframeWidth:a,iframeHeight:d,iframeId:this.b,paramString:this.H||"",serviceUrl:this.L};this.Bc();var i=u;if(c&&(1===c||2===c||3===c)){var f=i="auto",g;if(1===c)g="inline-block",i=a+"px",f=d+"px";else if(2===c||3===c)g="block",i="100%",f=+d+10+"px";b.widthValue=i;b.heightValue=f;b.displayValue=g;c=this.xa;c.setAttribute("width",i);c.setAttribute("height",
f);c.style.cssText=this.Nb("width:{widthValue};height:{heightValue};display:{displayValue};",b);i=n}b=this.Nb('<iframe id="{iframeId}" {srcAttrName}="{serviceUrl}{paramString}" width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true" ></iframe>',b);this.xa.innerHTML=b;this.Ca=e.s(this.b);i&&(this.q=this.Ca.parentNode);this.Zb();this.Jc()}},Zb:function(){var c=this.type,a=this.Ca,d=this.q;if(c){var b=
1;if(2===c)b=2;else if(3===c)b=1;else if(1!==c&&0!==c&&this.q){this.q.style.display="none";return}var i=2===c||3===c,g="";switch(c){case 2:case 3:var g="display:none;",h="";this.h.g&&7>this.h.g&&(h="_background-image:none;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+b+".png');");b=i?'<div id="'+this.b+'WrapToggle" style="z-index:2147483646;cursor:pointer;position:absolute;right:0;'+this.d+":0;width:40px;height:100%;background-color:"+
this.backgroundColor+';"><div style="width:20px;height:22px;position:absolute;top:50%;margin-top:-11px;left:50%;margin-left:-10px;background:no-repeat url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk'+b+".png);"+h+'"></div></div>':"";i=i?'<div id="'+this.b+'WrapBk" style="'+this.d+":0;left:0;position:absolute;width:100%;height:100%;background-color:"+this.backgroundColor+";-moz-opacity:"+this.ka/100+";filter:alpha(opacity="+this.ka+");opacity:"+this.ka/100+';"></div>':"";h="";e.B()?
1===c?h="position:fixed;top:0;":2===c?h="position:fixed;top:0;width:100%;":3===c&&(h="position:fixed;bottom:0;width:100%;"):1===c?h="position:absolute;top:0;":2===c?h="position:absolute;top:0;width:100%;":3===c&&(h="position:absolute;top:"+(f.G(window)+f.o(window)-this.width)+"px;width:100%;");d.insertAdjacentHTML("afterBegin",i+b);d.style.cssText=[g,"height:",this.height+10,"px;right:0;z-index:2147483646;text-align:center;font-size:0;_overflow-y:hidden;",h].join("");a.style.cssText="position:relative;margin:5px 0;";
this.mb=e.s(""+this.b+"WrapToggle");this.Ia=this.Hc("DIV",this.mb);this.S=e.s(this.b+"WrapBk");this.M()}}},Ha:function(){var c=this.e,a=this.r,d=this;E(["viewWatch"],function(b){b.register({id:c,wrapperId:a,logType:"block",extra:"ch="+d.$+"&jk="+d.ra+"&n="+d.ha})},n)},Jc:function(){var c=this,d=c.q,b=c.type,i=c.Ca,c=this;this.d?this.Kc?d.parentNode.removeChild(d):(setTimeout(function(){d.style.display="block";if(2===b||3===b){var a=i.getAttribute("_src");a&&(i.setAttribute("src",a),i.removeAttribute("_src"),
c.Ha())}},this.w),this.z&&setTimeout(function(){d.style.display="none"},this.w+this.z)):this.Ha();this.mb&&(2===this.type||3===this.type)&&e.bind(this.mb,"click",a.i(this.nb,this));e.bind(window,"scroll",a.i(this.pa,this));e.bind(window,"resize",a.i(this.pa,this))},Bc:function(){for(var c=1;2>=c;c++)(function(c){var a="bkimg_"+ +new Date+Math.floor(1E5*Math.random()),d=window[a]=new Image;d.onload=d.onerror=function(){d.onload=d.onerror=s;d=window[a]=s};d.src="http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+
c+".png"})(c)},nb:function(){this.wa?this.bb():this.show()},ua:function(c){if(!this.Z){this.Z=n;var a=this.q,d=this.S,b=this.Ca,e=this.d,i=a.offsetHeight,f=Math.round(this.Pa/i),g=0,h=this;c&&(a.style.width="100%");var m=+new Date,r=setInterval(function(){var a=g=Math.round((+new Date-m)/f),j=a;c&&(j=i-a);d.style[e]=-j+"px";b.style[e]=-j+"px";a>=i&&(h.Z=u,(h.wa=c)&&"top"===e||!c&&"bottom"===e?h.h.g&&7>h.h.g?h.Ia.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png');":
h.Ia.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png)":h.h.g&&7>h.h.g?h.Ia.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png');":h.Ia.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png)",j=i,c&&(j=0),d.style[e]=-j+"px",b.style[e]=-j+"px",clearInterval(r))},f)}},show:function(){(this.v||this.j)&&this.Dc(this.J);this.ua(n)},
bb:function(){(this.v||this.j)&&this.Ga();this.ua(u)},la:function(a){var d;a?(d=document.getElementById(a),a+="placeholder"):(d=this.q||document.getElementById(this.r),a=this.r+"placeholder");var b=document.createElement("div");b.id=a;b.align&&(b.align=d.getAttribute("align"));b.style.width=""+parseInt(d.getAttribute("width"),10)+"px";b.style.height=""+parseInt(d.getAttribute("height"),10)+"px";b.style.margin="0";b.style.padding="0";b.style.background="none";b.style.border="none";1===this.type&&(b.style.display=
"inline-block");d.parentNode.insertBefore(b,d);return n},ib:function(a){a=document.getElementById(a?a+"placeholder":this.r+"placeholder");a.parentNode.removeChild(a);return n},pb:function(a){var d=this.ob;return this.k(a?document.getElementById(a):this.q||document.getElementById(this.r)).top<d?d:u},Ic:function(a){var d=this.ob;return this.k(a?document.getElementById(a):this.q||document.getElementById(this.r)).top<d?d:u}})});return{render:function(a,c){switch(parseInt(a._html.xuanting,10)){case 1:a.displayType=
"inlay-float";break;case 2:a.displayType="float-top";break;case 3:a.displayType="float-bottom";break;default:a.displayType="inlay-float"}var b=i.qa(a);b.backgroundColor=a._html.rss1||"#666";b.backgroundOpacity=parseInt(a._html.opacity||60,10);var e=i.Ba(b.slotId,c),f={C:b.displayType,t:b.styleType,N:b.stuffType};if(!i.Aa(f))return u;(new d({xa:e,e:b.slotId,type:b.xuantingType,src:"",width:b.slotWidth,height:b.slotHeight,backgroundColor:b.backgroundColor,ka:b.backgroundOpacity,t:b.styleType,lb:b.tn,
$:b.channel,ha:b.unionAccount,za:b.adIndex,ra:b.pvId,w:b.delayIn,z:b.delayOut,v:b.sessionSync,j:b.closeFor,H:b.paramString,L:b.serviceUrl})).jb();i.sa(f)}}});
})();